[package]
name = "bench_thomas_vs_elrendio"
version = "0.1.0"
authors = ["Elrendio <oscar.walter@ens.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
